# Generated by Django 2.2 on 2022-03-22 10:05

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='School',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('province', models.CharField(max_length=128, verbose_name='省')),
                ('city', models.CharField(max_length=128, verbose_name='市')),
                ('region', models.CharField(max_length=128, verbose_name='区')),
                ('address', models.CharField(max_length=256, verbose_name='详细地址')),
                ('name', models.CharField(max_length=128, verbose_name='学校名')),
                ('week_diff_first', models.SmallIntegerField(default=0, null=True)),
                ('week_diff_second', models.SmallIntegerField(default=0, null=True)),
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('update_time', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('is_delete', models.BooleanField(default=False, verbose_name='逻辑删除标记')),
            ],
            options={
                'verbose_name': '学校表',
                'verbose_name_plural': '学校表',
                'db_table': 'school',
            },
        ),
    ]
