# Generated by Django 2.2 on 2022-03-24 08:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schools', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='school',
            name='week_num',
            field=models.SmallIntegerField(default=20, null=True, verbose_name='本学期总周数'),
        ),
        migrations.AlterField(
            model_name='school',
            name='week_diff_first',
            field=models.SmallIntegerField(default=0, null=True, verbose_name='上学期自然周差'),
        ),
        migrations.AlterField(
            model_name='school',
            name='week_diff_second',
            field=models.SmallIntegerField(default=0, null=True, verbose_name='下学期自然周差'),
        ),
    ]
