# Generated by Django 2.2 on 2022-03-24 09:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schools', '0002_auto_20220324_1627'),
    ]

    operations = [
        migrations.AddField(
            model_name='school',
            name='first_week_date',
            field=models.DateField(null=True, verbose_name='第一周日期'),
        ),
        migrations.AlterField(
            model_name='school',
            name='week_num',
            field=models.SmallIntegerField(default=20, verbose_name='本学期总周数'),
        ),
    ]
