# Generated by Django 2.2 on 2022-03-24 09:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schools', '0003_auto_20220324_1701'),
    ]

    operations = [
        migrations.AlterField(
            model_name='school',
            name='first_week_date',
            field=models.DateTimeField(null=True, verbose_name='第一周日期'),
        ),
    ]
