# Generated by Django 2.2 on 2022-03-28 07:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('schools', '0004_auto_20220324_1744'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='school',
            table='exchangecourse_school',
        ),
    ]
