# Generated by Django 2.2 on 2022-03-28 08:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('schools', '0005_auto_20220328_1545'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='school',
            name='week_diff_first',
        ),
        migrations.RemoveField(
            model_name='school',
            name='week_diff_second',
        ),
    ]
