# Generated by Django 2.2 on 2022-03-24 08:58

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Schedule',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('week', models.SmallIntegerField(verbose_name='周次')),
                ('weekday', models.SmallIntegerField(choices=[(1, '星期一'), (2, '星期二'), (3, '星期三'), (4, '星期四'), (5, '星期五'), (6, '星期六'), (7, '星期日')], verbose_name='星期')),
                ('order', models.SmallIntegerField(verbose_name='节次')),
                ('time', models.DateTimeField(null=True, verbose_name='时间')),
            ],
            options={
                'verbose_name': '课程时间表',
                'verbose_name_plural': '课程时间表',
                'db_table': 'schedule',
            },
        ),
    ]
