# Generated by Django 2.2 on 2022-03-28 07:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('schedule', '0002_remove_schedule_time'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='schedule',
            table='exchangecourse_schedule',
        ),
    ]
