# Generated by Django 2.2 on 2022-03-22 10:05

import django.contrib.auth.models
import django.contrib.auth.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('schools', '0001_initial'),
        ('auth', '0011_update_proxy_permissions'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('username', models.CharField(error_messages={'unique': 'A user with that username already exists.'}, help_text='Required. 150 characters or fewer. Letters, digits and @/./+/-/_ only.', max_length=150, unique=True, validators=[django.contrib.auth.validators.UnicodeUsernameValidator()], verbose_name='username')),
                ('work_id', models.CharField(max_length=25, null=True, unique=True, verbose_name='工号')),
                ('icon', models.ImageField(null=True, upload_to='users', verbose_name='头像')),
                ('phone', models.CharField(max_length=11, verbose_name='电话')),
                ('email', models.CharField(max_length=256, null=True, verbose_name='邮箱')),
                ('is_grade', models.SmallIntegerField(choices=[(0, '普通用户'), (1, '一年级管理员'), (2, '二年级管理员'), (3, '三年级管理员'), (4, '四年级管理员'), (5, '五年级管理员'), (6, '六年级管理员')], default=0, verbose_name='年级管理员')),
                ('is_super', models.SmallIntegerField(choices=[(0, '普通用户'), (1, '一年级管理员'), (2, '二年级管理员'), (3, '三年级管理员'), (4, '四年级管理员'), (5, '五年级管理员'), (6, '六年级管理员')], default=0, verbose_name='总管理员')),
                ('is_active', models.BooleanField(default=True, verbose_name='有效用户')),
                ('wechat', models.CharField(max_length=128, null=True, verbose_name='微信号')),
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('update_time', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('is_delete', models.BooleanField(default=False, verbose_name='逻辑删除标记')),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.Group', verbose_name='groups')),
                ('school_id', models.ForeignKey(db_column='school_id', on_delete=django.db.models.deletion.CASCADE, to='schools.School', verbose_name='学校id')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.Permission', verbose_name='user permissions')),
            ],
            options={
                'verbose_name': '用户表',
                'verbose_name_plural': '用户表',
                'db_table': 'user',
            },
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
    ]
