# Generated by Django 2.2 on 2022-03-22 13:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('schools', '0001_initial'),
        ('users', '0002_auto_20220322_2018'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='school_id',
            new_name='school_obj',
        ),
        migrations.AlterUniqueTogether(
            name='user',
            unique_together={('username', 'school_obj')},
        ),
    ]
