# Generated by Django 2.2 on 2022-03-28 07:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_auto_20220323_1354'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='user',
            table='exchangecourse_user',
        ),
    ]
