# Generated by Django 2.2 on 2022-03-22 10:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0002_course_teacher_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='weekday',
            field=models.SmallIntegerField(choices=[(1, '星期一'), (2, '星期二'), (3, '星期三'), (4, '星期四'), (5, '星期五'), (6, '星期六'), (7, '星期日')], verbose_name='星期'),
        ),
    ]
