# Generated by Django 2.2 on 2022-03-23 05:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0004_auto_20220322_2120'),
    ]

    operations = [
        migrations.RenameField(
            model_name='course',
            old_name='class_obj',
            new_name='class_id',
        ),
        migrations.RenameField(
            model_name='course',
            old_name='teacher_obj',
            new_name='teacher_id',
        ),
    ]
