# Generated by Django 2.2 on 2022-03-25 09:12

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0008_auto_20220324_1756'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='end_time',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now, verbose_name='下课时间'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='course',
            name='start_time',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now, verbose_name='上课时间'),
            preserve_default=False,
        ),
    ]
