# Generated by Django 2.2 on 2022-03-28 07:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0009_auto_20220325_1712'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='course',
            name='schedule_id',
        ),
        migrations.AlterModelTable(
            name='course',
            table='exchangecourse_course',
        ),
        migrations.AlterModelTable(
            name='coursetime',
            table='exchangecourse_course_time',
        ),
    ]
