# Generated by Django 2.2 on 2022-03-23 11:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('verifications', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='smscode',
            name='phone',
            field=models.CharField(max_length=11, unique=True, verbose_name='手机号'),
        ),
    ]
