# Generated by Django 2.2 on 2022-03-28 07:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('verifications', '0002_auto_20220323_1951'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='smscode',
            table='exchangecourse_smscode',
        ),
    ]
