# 数据库
# MYSQL_NAME = 'excourse_v1'
# MYSQL_HOST = 'localhost'
# MYSQL_PORT = '3306'
# MYSQL_USER = 'root'
# MYSQL_PASSWORD = 'yiner0326'
MYSQL_NAME = 'exchangecourse_test'
MYSQL_HOST = 'rm-bp11xcn500fcp5l8auo.mysql.rds.aliyuncs.com'
MYSQL_PORT = '3306'
MYSQL_USER = 'exchangecourse_test'
MYSQL_PASSWORD = 'luoxilimit1012_exchangecourse'
