# Generated by Django 2.2 on 2022-03-22 10:05

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Application',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reason', models.CharField(max_length=256, verbose_name='申请理由')),
                ('type', models.SmallIntegerField(choices=[(0, '调课'), (1, '代课')], default=0, verbose_name='申请类型')),
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name='申请时间')),
                ('handle_time', models.DateTimeField(null=True, verbose_name='处理时间')),
                ('fail_time', models.DateTimeField(verbose_name='到期时间')),
                ('applicant_confirm', models.SmallIntegerField(choices=[(0, '未确认'), (1, '确认且同意'), (2, '确认且拒绝')], default=0, verbose_name='申请方是否确认')),
                ('solver_confirm', models.SmallIntegerField(choices=[(0, '未确认'), (1, '确认且同意'), (2, '确认且拒绝')], default=0, verbose_name='目标方是否确认')),
                ('overdue', models.BooleanField(default=False, verbose_name='是否过期')),
                ('update_time', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('is_delete', models.BooleanField(default=False, verbose_name='逻辑删除标记')),
            ],
        ),
    ]
