# Generated by Django 2.2 on 2022-03-22 10:05

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('applications', '0002_application_applicant_course_id'),
        ('courses', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='application',
            name='handler_id',
            field=models.ForeignKey(db_column='handler_id', null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='处理人id'),
        ),
        migrations.AddField(
            model_name='application',
            name='target_course_id',
            field=models.ForeignKey(db_column='target_course_id', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='target_course_id', to='courses.Course', verbose_name='目标课程id'),
        ),
    ]
