# Generated by Django 2.2 on 2022-03-22 13:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('applications', '0003_auto_20220322_1805'),
    ]

    operations = [
        migrations.RenameField(
            model_name='application',
            old_name='applicant_course_id',
            new_name='applicant_course_obj',
        ),
        migrations.RenameField(
            model_name='application',
            old_name='handler_id',
            new_name='handler_obj',
        ),
        migrations.RenameField(
            model_name='application',
            old_name='target_course_id',
            new_name='target_course_obj',
        ),
    ]
