# Generated by Django 2.2 on 2022-03-23 05:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('applications', '0004_auto_20220322_2120'),
    ]

    operations = [
        migrations.RenameField(
            model_name='application',
            old_name='applicant_course_obj',
            new_name='applicant_course_id',
        ),
        migrations.RenameField(
            model_name='application',
            old_name='handler_obj',
            new_name='handler_id',
        ),
        migrations.RenameField(
            model_name='application',
            old_name='target_course_obj',
            new_name='target_course_id',
        ),
    ]
