# Generated by Django 2.2 on 2022-03-28 03:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('applications', '0009_auto_20220328_1109'),
    ]

    operations = [
        migrations.AlterField(
            model_name='application',
            name='accept',
            field=models.BooleanField(null=True, verbose_name='是否接受'),
        ),
        migrations.AlterField(
            model_name='application',
            name='refuse_reason',
            field=models.CharField(max_length=256, null=True, verbose_name='拒绝原因'),
        ),
    ]
