# Generated by Django 2.2 on 2022-03-22 13:20

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('classes', '0002_auto_20220322_2120'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('courses', '0003_auto_20220322_1850'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='course',
            name='class_id',
        ),
        migrations.RemoveField(
            model_name='course',
            name='teacher_id',
        ),
        migrations.AddField(
            model_name='course',
            name='class_obj',
            field=models.ForeignKey(db_column='class_id', default=1, on_delete=django.db.models.deletion.CASCADE, to='classes.Class', verbose_name='班级id'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='course',
            name='teacher_obj',
            field=models.ForeignKey(db_column='teacher_id', default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='教师id'),
            preserve_default=False,
        ),
    ]
