# Generated by Django 2.2 on 2022-03-23 14:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0005_auto_20220323_1354'),
    ]

    operations = [
        migrations.CreateModel(
            name='CourseTime',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('week', models.SmallIntegerField(verbose_name='周次')),
                ('weekday', models.SmallIntegerField(choices=[(1, '星期一'), (2, '星期二'), (3, '星期三'), (4, '星期四'), (5, '星期五'), (6, '星期六'), (7, '星期日')], verbose_name='星期')),
                ('order', models.SmallIntegerField(verbose_name='节次')),
            ],
            options={
                'verbose_name': '课程时间表',
                'verbose_name_plural': '课程时间表',
                'db_table': 'course_time',
            },
        ),
        migrations.AddField(
            model_name='course',
            name='course_time_id',
            field=models.ForeignKey(db_column='course_time_id', default=1, on_delete=django.db.models.deletion.CASCADE, to='courses.CourseTime', verbose_name='课程时间id'),
        ),
    ]
