# Generated by Django 2.2 on 2022-03-23 14:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0006_auto_20220323_2258'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='course_time_id',
            field=models.ForeignKey(db_column='course_time_id', null=True, on_delete=django.db.models.deletion.CASCADE, to='courses.CourseTime', verbose_name='课程时间id'),
        ),
    ]
