# Generated by Django 2.2 on 2022-03-24 09:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('schedule', '0001_initial'),
        ('courses', '0007_auto_20220323_2259'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='course',
            name='course_time_id',
        ),
        migrations.AddField(
            model_name='course',
            name='schedule_id',
            field=models.ForeignKey(db_column='schedule_id', null=True, on_delete=django.db.models.deletion.CASCADE, to='schedule.Schedule', verbose_name='课程时间id'),
        ),
    ]
