# Generated by Django 2.2 on 2022-03-22 13:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('classes', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='class',
            old_name='school_id',
            new_name='school_obj',
        ),
    ]
