# Generated by Django 2.2 on 2022-03-22 10:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('courses', '0001_initial'),
        ('applications', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='application',
            name='applicant_course_id',
            field=models.ForeignKey(db_column='applicant_course_id', on_delete=django.db.models.deletion.CASCADE, related_name='applicant_course_id', to='courses.Course', verbose_name='申请课程id'),
        ),
    ]
