# Generated by Django 2.2 on 2022-03-23 08:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('applications', '0005_auto_20220323_1352'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='application',
            options={'verbose_name': '申请表', 'verbose_name_plural': '申请表'},
        ),
        migrations.AlterModelTable(
            name='application',
            table='application',
        ),
    ]
