# Generated by Django 2.2 on 2022-03-23 08:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('applications', '0007_auto_20220323_1654'),
    ]

    operations = [
        migrations.AlterField(
            model_name='application',
            name='applicant_course_id',
            field=models.ForeignKey(db_column='applicant_course_id', on_delete=django.db.models.deletion.CASCADE, related_name='applicant_course_id', to='courses.Course', verbose_name='申请课程id'),
        ),
    ]
