# Generated by Django 2.2 on 2022-03-28 03:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('applications', '0008_auto_20220323_1654'),
    ]

    operations = [
        migrations.AddField(
            model_name='application',
            name='accept',
            field=models.BooleanField(default=False, verbose_name='是否接受'),
        ),
        migrations.AddField(
            model_name='application',
            name='refuse_reason',
            field=models.CharField(default='', max_length=256, verbose_name='拒绝原因'),
        ),
    ]
