# Generated by Django 2.2 on 2022-03-28 03:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('applications', '0010_auto_20220328_1116'),
    ]

    operations = [
        migrations.RenameField(
            model_name='application',
            old_name='refuse_reason',
            new_name='cancel_reason',
        ),
    ]
