# Generated by Django 2.2 on 2022-03-28 07:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('applications', '0011_auto_20220328_1125'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='application',
            name='accept',
        ),
        migrations.AlterModelTable(
            name='application',
            table='exchangecourse_application',
        ),
    ]
