# Generated by Django 2.2 on 2022-03-28 07:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('classes', '0003_auto_20220323_1352'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='class',
            table='exchangecourse_class',
        ),
    ]
